### PR TITLE
Fix inconsistent undo and make `help COMMAND_WORD` examples location based

### LINKED ISSUE #146: Inconsistent Undo functionality with theme changes
## Description
While `ThemeCommand` is marked as state-mutating and `UndoCommand` supports it, changing the theme in command console can be undone with the `undo` command, but not changing it from the View Tab. 

## Suggested Fix:
Either set theme changes as non state-mutating and let the user manually change back any past theme changes through the GUI.

### LINKED ISSUE #150: Find command help message still shows persons example instead of locations
## Description:

Currently, typing `help find` still displays the following:

```
find: Finds all locations whose fields match the specified criteria (case-insensitive) and displays them as a list with index numbers.
Name search is based on substring match of any provided keywords.
Search by multiple prefixes (n/, p/, e/, a/, t/, d/) uses AND logic.
Parameters: [NAME_KEYWORD]... [n/NAME] [p/PHONE] [e/EMAIL] [a/ADDRESS] [t/TAG]... [d/DATE]...
Example: find alice n/bob p/9123 e/johndoe@example.com t/important a/Clementi d/2024-01-15
```

## Suggested Fix:

Change it all to Location based examples instead for consistency with the product. Also, check the other help messages for other commands to ensure no persons examples remain from the original AB3.

### PR DESCRIPTION
**Pull request by foysalAhm10**
## Fixes

1. Made undo command non state-mutating. Made more sense then keeping it state mutating and wiring in the view tab which was the issue. Updated UG and DG. 
i. Fixes #146
2. Made the `help edit` and `help find` examples location based. Also updated UG.
i. Fixes #150

### CODE REVIEW

File: src/main/java/seedu/address/logic/commands/ThemeCommand.java [hunk 1]
```diff
@@ -15,7 +15,7 @@ public class ThemeCommand extends Command {
     public static final String COMMAND_WORD = "theme";
 
     public static final String MESSAGE_USAGE = COMMAND_WORD + ": Changes the application theme.\n"
-            + "Parameters: THEME_TYPE (light OR dark)\n"
+            + "Parameters: THEME_NAME (light OR dark)\n"
```
Comment (stanvewidjaja) [inline src/main/java/seedu/address/logic/commands/ThemeCommand.java]: Looks good.

I will need to settle merge conflicts with these since I already opened a PR for "inconsistent help message formatting" (#154).
